import type { HistorySurfaceDto } from "./history-surface";

/** QA-only, deterministic history. It is never mixed into a live response. */
export function buildDemoHistory(now: Date): HistorySurfaceDto {
  return {
    syntheticLabel: "Synthetic data",
    asOf: now.toISOString(),
    period: "Demo sample · all qualifying actionable decisions",
    modelVersion: "phase-1-experimental.v1",
    hasMore: false,
    nextCursor: null,
    decisions: [
      {
        id: "demo-1",
        decidedAt: "2026-09-01T11:04:00.000Z",
        competition: "Premier Synthetic League",
        homeTeam: "Northbridge United",
        awayTeam: "Riverside Athletic",
        market: "Full-time 1X2",
        selection: "Home",
        decisionState: "STRONG_EDGE",
        modelProbability: "0.6",
        oddsAtDecision: "1.91",
        fairOdds: "1.67",
        expectedValue: "0.146",
        finalScore: "0–1",
        settlement: "LOSS",
        closingOdds: "1.71",
        clv: "0.116959064327",
        modelVersion: "phase-1-experimental.v1",
        priceQuality: "POSITIVE_CLV",
      },
      {
        id: "demo-2",
        decidedAt: "2026-09-02T10:21:00.000Z",
        competition: "Premier Synthetic League",
        homeTeam: "Harbor Rovers",
        awayTeam: "Oldtown FC",
        market: "Over/Under 2.5",
        selection: "Over 2.5",
        decisionState: "EDGE",
        modelProbability: "0.57",
        oddsAtDecision: "1.95",
        fairOdds: "1.75",
        expectedValue: "0.1115",
        finalScore: "2–1",
        settlement: "WIN",
        closingOdds: "2.02",
        clv: "-0.034653465347",
        modelVersion: "phase-1-experimental.v1",
        priceQuality: "NEGATIVE_CLV",
      },
      {
        id: "demo-3",
        decidedAt: "2026-09-03T13:18:00.000Z",
        competition: "Premier Synthetic League",
        homeTeam: "Lakeside Albion",
        awayTeam: "Metro Vale",
        market: "Full-time 1X2",
        selection: "Away",
        decisionState: "EDGE_DISAPPEARED",
        modelProbability: "0.48",
        oddsAtDecision: "2.4",
        fairOdds: "2.08",
        expectedValue: "0.152",
        finalScore: "1–2",
        settlement: "WIN",
        closingOdds: "2.28",
        clv: "0.052631578947",
        modelVersion: "phase-1-experimental.v1",
        priceQuality: "POSITIVE_CLV",
      },
      {
        id: "demo-4",
        decidedAt: "2026-09-04T09:50:00.000Z",
        competition: "Premier Synthetic League",
        homeTeam: "Eastvale City",
        awayTeam: "Kingsport FC",
        market: "Full-time 1X2",
        selection: "Home",
        decisionState: "WATCH",
        modelProbability: "0.51",
        oddsAtDecision: "2.05",
        fairOdds: "1.96",
        expectedValue: "0.0455",
        finalScore: "—",
        settlement: "VOID",
        closingOdds: null,
        clv: null,
        modelVersion: "phase-1-experimental.v1",
        priceQuality: "UNAVAILABLE",
      },
    ],
  };
}
