import type { CustomerMatchDto, CustomerTodayDto } from "@velyq/contracts";
import type { DecimalString } from "@velyq/decimal";

const d = (value: string) => value as DecimalString;
export const customerToday: CustomerTodayDto = {
  syntheticLabel: "Synthetic data",
  asOf: "2026-09-04T10:00:00.000Z",
  matches: [
    {
      eventId: "73000000-0000-4000-8000-000000000001",
      homeTeam: "Northbridge United",
      awayTeam: "Riverside Athletic",
      competition: "Premier Synthetic League",
      startsAt: "2026-09-04T18:30:00.000Z",
      syntheticLabel: "Synthetic data",
      freshness: "FRESH",
      selection: "Home",
      recommendation: "STRONG_EDGE",
      modelProbability: d("0.6"),
      impliedProbability: d("0.540540540541"),
      fairOdds: d("1.666666666666666666666666666667"),
      currentOdds: d("1.85"),
      openingOdds: d("2.1"),
      probabilityEdge: d("0.059459459459"),
      expectedValue: d("0.11"),
      lineup: "OFFICIAL",
      quality: {
        grade: "A",
        score: d("1"),
        policyVersion: "phase-1-quality.v1",
        reasonCodes: [],
      },
      trace: {
        modelVersion: "phase-1-experimental.v1",
        maturity: "EXPERIMENTAL",
        calibrationVersion: "identity.v1",
        scoreVersion: "edge.v1",
        featureCutoff: "2026-09-04T10:00:00.000Z",
      },
    },
    {
      eventId: "73000000-0000-4000-8000-000000000002",
      homeTeam: "Eastvale City",
      awayTeam: "Kingsport FC",
      competition: "Premier Synthetic League",
      startsAt: "2026-09-04T20:00:00.000Z",
      syntheticLabel: "Synthetic data",
      freshness: "FRESH",
      selection: "Home",
      recommendation: "WAIT_FOR_LINEUP",
      modelProbability: null,
      impliedProbability: d("0.476190476190"),
      fairOdds: null,
      currentOdds: d("2.1"),
      openingOdds: d("2.2"),
      probabilityEdge: null,
      expectedValue: null,
      lineup: "MISSING",
      quality: {
        grade: "B",
        score: d("0.75"),
        policyVersion: "phase-1-quality.v1",
        reasonCodes: ["MISSING_LINEUP"],
      },
      trace: {
        modelVersion: "phase-1-experimental.v1",
        maturity: "EXPERIMENTAL",
        calibrationVersion: "identity.v1",
        scoreVersion: "edge.v1",
        featureCutoff: "2026-09-04T10:00:00.000Z",
      },
    },
    {
      eventId: "73000000-0000-4000-8000-000000000003",
      homeTeam: "Harbor Rovers",
      awayTeam: "Oldtown FC",
      competition: "Premier Synthetic League",
      startsAt: "2026-09-04T21:30:00.000Z",
      syntheticLabel: "Synthetic data",
      freshness: "STALE",
      selection: "Draw",
      recommendation: "NO_BET",
      modelProbability: null,
      impliedProbability: null,
      fairOdds: null,
      currentOdds: null,
      openingOdds: null,
      probabilityEdge: null,
      expectedValue: null,
      lineup: "EXPECTED",
      quality: {
        grade: "F",
        score: d("0"),
        policyVersion: "phase-1-quality.v1",
        reasonCodes: ["STALE_DATA", "MISSING_PRICE"],
      },
      trace: {
        modelVersion: "phase-1-experimental.v1",
        maturity: "EXPERIMENTAL",
        calibrationVersion: "identity.v1",
        scoreVersion: "edge.v1",
        featureCutoff: "2026-09-04T10:00:00.000Z",
      },
    },
  ],
};
export function findCustomerMatch(
  eventId: string,
): CustomerMatchDto | undefined {
  return customerToday.matches.find((match) => match.eventId === eventId);
}
