import { adminAuditEvents } from "./audit.js";
import {
  bookmakers,
  eventMarketOutcomes,
  eventMarkets,
  marketDefinitions,
  oddsObservations,
  outcomeDefinitions,
  providerMarketMappings,
} from "./market.js";
import {
  calibrationVersions,
  dataQualityAssessments,
  dataQualityPolicyVersions,
  lineupObservations,
  modelDefinitions,
  modelVersions,
  predictionInputs,
  predictionRuns,
  predictions,
  radarEvidence,
  scoreDefinitionVersions,
  scoreResults,
} from "./intelligence.js";
import {
  competitions,
  eventParticipants,
  events,
  participants,
  sports,
} from "./catalog.js";
import {
  jobs,
  providerPolicyVersions,
  providerSyncRuns,
  providers,
  sourceObservations,
} from "./operations.js";
import { permissions, rolePermissions, roles, userRoles } from "./private.js";
import { profiles } from "./public.js";

export const databaseSchema = {
  adminAuditEvents,
  bookmakers,
  calibrationVersions,
  competitions,
  dataQualityAssessments,
  dataQualityPolicyVersions,
  eventMarketOutcomes,
  eventMarkets,
  eventParticipants,
  events,
  jobs,
  lineupObservations,
  marketDefinitions,
  modelDefinitions,
  modelVersions,
  oddsObservations,
  outcomeDefinitions,
  participants,
  permissions,
  predictionInputs,
  predictionRuns,
  predictions,
  profiles,
  providerMarketMappings,
  providerPolicyVersions,
  providerSyncRuns,
  providers,
  radarEvidence,
  rolePermissions,
  roles,
  scoreDefinitionVersions,
  scoreResults,
  sourceObservations,
  sports,
  userRoles,
} as const;
