import { adminAuditEvents } from "./audit.js";
import {
  bookmakers,
  eventMarketOutcomes,
  eventMarkets,
  marketDefinitions,
  oddsObservations,
  outcomeDefinitions,
  providerMarketMappings,
} from "./market.js";
import {
  calibrationVersions,
  dataQualityAssessments,
  dataQualityPolicyVersions,
  decisions,
  eventResults,
  forecasts,
  lineupObservations,
  modelDefinitions,
  modelVersions,
  marketSettlements,
  predictionInputs,
  predictionRuns,
  predictions,
  radarEvidence,
  scoreDefinitionVersions,
  scoreResults,
} from "./intelligence.js";
import {
  competitionIdentities,
  competitions,
  eventIdentities,
  eventParticipants,
  events,
  participants,
  sports,
} from "./catalog.js";
import {
  jobs,
  providerIngestionRuns,
  providerOddsRequests,
  providerPolicyVersions,
  providerQuotaState,
  providerSyncRuns,
  providers,
  sourceObservations,
} from "./operations.js";
import {
  billingCustomers,
  billingEvents,
  permissions,
  planDefinitions,
  rolePermissions,
  roles,
  subscriptions,
  userRoles,
} from "./private.js";
import { profiles } from "./public.js";

export const databaseSchema = {
  adminAuditEvents,
  billingCustomers,
  billingEvents,
  bookmakers,
  calibrationVersions,
  competitionIdentities,
  competitions,
  dataQualityAssessments,
  dataQualityPolicyVersions,
  decisions,
  eventIdentities,
  eventResults,
  eventMarketOutcomes,
  eventMarkets,
  eventParticipants,
  events,
  forecasts,
  jobs,
  lineupObservations,
  marketDefinitions,
  marketSettlements,
  modelDefinitions,
  modelVersions,
  oddsObservations,
  outcomeDefinitions,
  participants,
  permissions,
  planDefinitions,
  predictionInputs,
  predictionRuns,
  predictions,
  profiles,
  providerMarketMappings,
  providerIngestionRuns,
  providerOddsRequests,
  providerPolicyVersions,
  providerQuotaState,
  providerSyncRuns,
  providers,
  radarEvidence,
  rolePermissions,
  roles,
  scoreDefinitionVersions,
  scoreResults,
  sourceObservations,
  sports,
  subscriptions,
  userRoles,
} as const;
