import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

import {
  runEnsembleBacktest,
  type EnsembleResult,
  type SupportedMarketCode,
} from "../../packages/research/src/index.js";
import { loadCorpus } from "./historical-corpus.js";

/**
 * Runs the market-informed ensemble's walk-forward evaluation and writes the
 * verdict, human-readable and machine-readable.
 *
 * The verdict is the deliverable, not the model. `MATCHES_MARKET` and
 * `UNDERPERFORMS_MARKET` are real answers, and a report that could only
 * express `IMPROVES_MARKET` would be worthless — so the numbers behind the
 * verdict are all here, per competition and per market, with the losing
 * segments included.
 *
 * Usage:
 *   pnpm model:ensemble
 */

const MARKET_LABELS: Readonly<Record<string, string>> = {
  FOOTBALL_FULL_TIME_1X2: "Full-time 1X2",
  FOOTBALL_FULL_TIME_TOTAL: "Over/under 2.5",
  FOOTBALL_FULL_TIME_BTTS: "Both teams to score",
};

function round(value: number | null | undefined, places = 4): string {
  return value === null || value === undefined || !Number.isFinite(value)
    ? "—"
    : value.toFixed(places);
}

function signed(value: number | null | undefined, places = 5): string {
  if (value === null || value === undefined || !Number.isFinite(value))
    return "—";
  return `${value > 0 ? "+" : ""}${value.toFixed(places)}`;
}

type Rollup = Readonly<{
  marketCode: SupportedMarketCode;
  samples: number;
  market: number;
  v1: number;
  v2: number;
  marketBrier: number;
  v1Brier: number;
  v2Brier: number;
  v2Calibration: number;
  segments: number;
  beaten: number;
}>;

/** Sample-weighted, so the smallest league cannot outvote the largest. */
export function rollupEnsemble(result: EnsembleResult): readonly Rollup[] {
  const byMarket = new Map<
    SupportedMarketCode,
    {
      samples: number;
      market: number;
      v1: number;
      v2: number;
      marketBrier: number;
      v1Brier: number;
      v2Brier: number;
      calibration: number;
      segments: number;
      beaten: number;
    }
  >();
  for (const row of result.perMarket) {
    if (!row.market || !row.modelV1 || !row.modelV2) continue;
    const entry = byMarket.get(row.marketCode) ?? {
      samples: 0,
      market: 0,
      v1: 0,
      v2: 0,
      marketBrier: 0,
      v1Brier: 0,
      v2Brier: 0,
      calibration: 0,
      segments: 0,
      beaten: 0,
    };
    const weight = row.holdoutSamples;
    entry.samples += weight;
    entry.market += row.market.logLoss * weight;
    entry.v1 += row.modelV1.logLoss * weight;
    entry.v2 += row.modelV2.logLoss * weight;
    entry.marketBrier += row.market.brier * weight;
    entry.v1Brier += row.modelV1.brier * weight;
    entry.v2Brier += row.modelV2.brier * weight;
    entry.calibration += row.modelV2.calibrationError * weight;
    entry.segments += 1;
    if ((row.deltaLogLossVsMarket ?? 0) < 0) entry.beaten += 1;
    byMarket.set(row.marketCode, entry);
  }
  return [...byMarket.entries()].map(([marketCode, entry]) => {
    const n = Math.max(1, entry.samples);
    return {
      marketCode,
      samples: entry.samples,
      market: entry.market / n,
      v1: entry.v1 / n,
      v2: entry.v2 / n,
      marketBrier: entry.marketBrier / n,
      v1Brier: entry.v1Brier / n,
      v2Brier: entry.v2Brier / n,
      v2Calibration: entry.calibration / n,
      segments: entry.segments,
      beaten: entry.beaten,
    };
  });
}

export function renderEnsembleReport(result: EnsembleResult): string {
  const rollups = rollupEnsemble(result);
  const lines: string[] = [];

  lines.push("# Market-informed model (football-market-ensemble.v1)");
  lines.push("");
  lines.push(
    "Generated by `pnpm model:ensemble` from the historical corpus. Do not edit by hand.",
  );
  lines.push("");
  lines.push(`## Verdict: **${result.verdict}**`);
  lines.push("");
  for (const reason of result.verdictReasons) lines.push(`- \`${reason}\``);
  lines.push("");
  lines.push("## The question, and why it is framed this way");
  lines.push("");
  lines.push(
    "The Phase-3 score model beats naive base rates everywhere and beats the de-vigged market almost nowhere. The honest reading is that the market is a far better prior than an independent model, so it belongs in the model as a *feature* rather than as something to be compared against at the end.",
  );
  lines.push("");
  lines.push(
    "This is multinomial logistic stacking, and deliberately the simplest thing that could work:",
  );
  lines.push("");
  lines.push("```");
  lines.push("score_k = intercept_k + marketWeight · log(p_market_k)");
  lines.push("                      + modelWeight  · log(p_model_k)");
  lines.push("p_k     = softmax(score)_k");
  lines.push("```");
  lines.push("");
  lines.push(
    "Four free parameters for a three-outcome market. With this few, a fitted `modelWeight` near zero is strong evidence that the football signal adds nothing — not a shrinkage artifact. The null hypothesis is that the market is already better.",
  );
  lines.push("");
  lines.push("## Fitted weights");
  lines.push("");
  lines.push(
    "| Market | marketWeight | modelWeight | Model contribution | Fitted on | Temperature |",
  );
  lines.push("| --- | --- | --- | --- | --- | --- |");
  for (const entry of result.ensembles)
    lines.push(
      `| ${MARKET_LABELS[entry.marketCode] ?? entry.marketCode} | ${round(entry.ensemble.marketWeight, 4)} | ${round(entry.ensemble.modelWeight, 4)} | ${(entry.modelContribution * 100).toFixed(1)}% | ${entry.ensemble.sampleCount} | ${entry.calibrator.temperature} |`,
    );
  lines.push("");
  lines.push("## Holdout, against the market baseline");
  lines.push("");
  lines.push(
    `Untouched holdout of ${result.holdoutRecords} matches from ${result.holdoutFrom}, after ${result.walkForwardCutoffs.length} walk-forward windows.`,
  );
  lines.push("");
  lines.push(
    "| Market | n | Market log loss | v1 | **v2** | Δ v2 − market | Market Brier | v1 | **v2** | v2 calib. err | Segments beaten |",
  );
  lines.push(
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
  );
  for (const rollup of rollups)
    lines.push(
      `| ${MARKET_LABELS[rollup.marketCode] ?? rollup.marketCode} | ${rollup.samples} | ${round(rollup.market)} | ${round(rollup.v1)} | **${round(rollup.v2)}** | ${signed(rollup.v2 - rollup.market)} | ${round(rollup.marketBrier)} | ${round(rollup.v1Brier)} | **${round(rollup.v2Brier)}** | ${round(rollup.v2Calibration)} | ${rollup.beaten}/${rollup.segments} |`,
    );
  lines.push("");
  lines.push("### Per competition, including the losing segments");
  lines.push("");
  lines.push(
    "| Competition | Market | n | Market LL | v1 LL | v2 LL | Δ vs market | v2 Brier | Δ Brier |",
  );
  lines.push("| --- | --- | --- | --- | --- | --- | --- | --- | --- |");
  for (const row of result.perMarket) {
    if (!row.market || !row.modelV2) continue;
    lines.push(
      `| ${row.competitionCode} | ${MARKET_LABELS[row.marketCode] ?? row.marketCode} | ${row.holdoutSamples} | ${round(row.market.logLoss)} | ${round(row.modelV1?.logLoss)} | ${round(row.modelV2.logLoss)} | ${signed(row.deltaLogLossVsMarket)} | ${round(row.modelV2.brier)} | ${signed(row.deltaBrierVsMarket)} |`,
    );
  }
  lines.push("");
  lines.push("## Does model-market disagreement carry information?");
  lines.push("");
  lines.push(
    "Every bucket boundary was fixed in advance and every populated bucket is reported. `observed` next to `market expected` is the whole test: if the model's disagreement has value, buckets where it is more bullish than the market should show the outcome occurring more often than the market expected.",
  );
  for (const entry of result.disagreement) {
    const populated = entry.buckets.filter((bucket) => bucket.samples > 0);
    if (populated.length === 0) continue;
    lines.push("");
    lines.push(`### ${MARKET_LABELS[entry.marketCode] ?? entry.marketCode}`);
    lines.push("");
    lines.push(
      "| model − market | n | mean disagreement | observed | market expected | model expected | mean closing move |",
    );
    lines.push("| --- | --- | --- | --- | --- | --- | --- |");
    for (const bucket of populated)
      lines.push(
        `| [${bucket.lowerBound.toFixed(2)}, ${bucket.upperBound.toFixed(2)}) | ${bucket.samples} | ${round(bucket.meanDisagreement)} | ${round(bucket.observedFrequency)} | ${round(bucket.marketExpectedFrequency)} | ${round(bucket.modelExpectedFrequency)} | ${bucket.meanClosingMovement === null ? "—" : signed(bucket.meanClosingMovement)} |`,
      );
  }
  lines.push("");
  lines.push("## Closing-line research (a different target)");
  lines.push("");
  lines.push(
    "Whether model-market disagreement predicts where the price goes next. This is **not** an outcome model: a signal that identifies prices the market later moves toward would be useful on its own, and could be present even where outcome prediction fails. `shortened` shares are given for both the bullish and bearish groups, because the bullish share alone says nothing — a market drifting toward everything would produce a high number with no signal in it.",
  );
  lines.push("");
  lines.push(
    "| Market | n | corr(disagreement, movement) | shortened when model bullish | when bearish | mean absolute movement |",
  );
  lines.push("| --- | --- | --- | --- | --- | --- |");
  for (const entry of result.closingLine) {
    if (!Number.isFinite(entry.study.disagreementMovementCorrelation)) continue;
    lines.push(
      `| ${MARKET_LABELS[entry.marketCode] ?? entry.marketCode} | ${entry.study.samples} | ${round(entry.study.disagreementMovementCorrelation)} | ${round(entry.study.shortenedWhenModelBullish)} | ${round(entry.study.shortenedWhenModelBearish)} | ${round(entry.study.meanAbsoluteMovement)} |`,
    );
  }
  lines.push("");
  lines.push("## Feature discipline");
  lines.push("");
  lines.push(
    "Two features are trained on, and both are reconstructible at any past cutoff: the de-vigged pre-closing market consensus, and the walk-forward-refitted score model. The closing price, current injuries and confirmed lineups are `EVIDENCE_ONLY_FEATURE` — available now, not reconstructible historically, and therefore usable as displayed evidence but never as model inputs. API-Sports' own predictions are an `EXTERNAL_BENCHMARK` and are never blended in.",
  );
  lines.push("");
  lines.push(
    "`assertTrainableFeatures` refuses a training set containing any non-modelled feature and names it, rather than filtering it out silently.",
  );
  lines.push("");
  return `${lines.join("\n")}\n`;
}

async function main() {
  const corpusDirectory =
    process.env["VELYQ_HISTORICAL_CORPUS_DIR"] ??
    "data/historical/football-data";
  const corpus = loadCorpus(corpusDirectory);
  if (corpus.matches.length === 0) throw new Error("HISTORICAL_CORPUS_EMPTY");

  const result = runEnsembleBacktest(corpus.matches, {
    initialTrainingDays: 1095,
    stepDays: 90,
    holdoutFraction: 0.15,
    devigMethod: "SHIN",
  });

  const outputDirectory =
    process.env["VELYQ_RESEARCH_DOCS_DIR"] ?? "docs/research";
  mkdirSync(outputDirectory, { recursive: true });
  const humanPath = path.join(outputDirectory, "football-market-ensemble.md");
  const machinePath = path.join(
    outputDirectory,
    "football-market-ensemble.json",
  );
  writeFileSync(humanPath, renderEnsembleReport(result), "utf8");
  writeFileSync(machinePath, `${JSON.stringify(result, null, 2)}\n`, "utf8");

  const artifactDirectory =
    process.env["VELYQ_MODEL_ARTIFACT_DIR"] ?? "data/historical/artifacts";
  mkdirSync(artifactDirectory, { recursive: true });
  /*
   * The fitted stackers are written beside the score-model artifact so
   * inference loads them rather than refitting. Kept in the gitignored
   * artifact directory for the same reason the score model is: it is derived
   * from a corpus whose redistribution terms are unresolved.
   */
  const ensemblePath = path.join(
    artifactDirectory,
    "football-market-ensemble.v1.json",
  );
  writeFileSync(
    ensemblePath,
    `${JSON.stringify(
      {
        modelCode: "FOOTBALL_MARKET_ENSEMBLE",
        version: "football-market-ensemble.v1",
        verdict: result.verdict,
        verdictReasons: result.verdictReasons,
        trainingCutoff: result.holdoutFrom,
        ensembles: result.ensembles,
        generatedAt: result.generatedAt,
      },
      null,
      2,
    )}\n`,
    "utf8",
  );

  process.stdout.write(
    `${JSON.stringify(
      {
        verdict: result.verdict,
        verdictReasons: result.verdictReasons,
        humanPath,
        machinePath,
        ensemblePath,
        holdoutRecords: result.holdoutRecords,
      },
      null,
      2,
    )}\n`,
  );
}

if (process.argv[1]?.endsWith("ensemble-report.ts")) void main();
