/**
 * Writes the Cloudflare `_headers` rules for statically served pages.
 *
 * Prerendered HTML is served by Cloudflare's asset layer without invoking the
 * Worker — which is the whole point, but it also means `proxy.ts` never runs
 * and therefore never attaches the security headers. `_headers` is the only
 * mechanism that applies to asset responses, so the same baseline has to be
 * expressed there too.
 *
 * The values are imported from the single source both paths share, so the
 * static and dynamic responses cannot drift apart silently;
 * `apps/web/test/security-headers.test.ts` asserts they match.
 */
import { appendFileSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../..");

const OUT = resolve(
  process.argv[2] ?? resolve(repoRoot, "apps/web/dist/client/_headers"),
);

/*
 * Read the canonical list out of the TypeScript source rather than importing
 * it: this script runs as plain Node during the build, and duplicating the
 * values here is exactly the drift the test guards against.
 */
const source = readFileSync(
  resolve(repoRoot, "apps/web/security-headers.ts"),
  "utf8",
);
const headers = [
  ...source.matchAll(/\[\s*"([^"]+)",\s*\n?\s*"([^"]+)",?\s*\]/g),
].map(([, key, value]) => [key, value]);
if (headers.length === 0) {
  console.error("No security headers parsed from security-headers.ts");
  process.exit(1);
}

const existing = (() => {
  try {
    return readFileSync(OUT, "utf8");
  } catch {
    return "";
  }
})();

if (existing.includes("# velyq security headers")) {
  console.log("_headers already carries the security baseline");
} else {
  const block = [
    "",
    "# velyq security headers (generated by tooling/scripts/static-headers.mjs)",
    "# Applied to statically served pages, which never reach proxy.ts.",
    "/*",
    ...headers.map(([key, value]) => `  ${key}: ${value}`),
    "",
  ].join("\n");
  appendFileSync(OUT, block, "utf8");
  console.log(`wrote ${headers.length} security headers into ${OUT}`);
}

// Prerendered HTML must never be cached as immutable: a redeploy changes it.
const html = readFileSync(OUT, "utf8");
if (!html.includes("# velyq html cache")) {
  writeFileSync(
    OUT,
    `${html}\n# velyq html cache\n/*.html\n  Cache-Control: public, max-age=0, must-revalidate\n`,
    "utf8",
  );
}
